### ISSUE TITLE
鳴き牌のレンダリング

### ISSUE THREAD

**Issue by youseegreen** [senskids/CustomMahjong#4]
### 実装すること
- ポンやチー、カンの時に誰から鳴いたかわかるように牌を曲げる
- 加槓時の牌重ね表現の描画

**Comment by takumi765** [comment]
ポンだけやりました

**Comment by takumi765** [comment]
ポンとカンをしました

**Comment by takumi765** [comment]
直立しました．

**Comment by youseegreen** [comment]
### まだ残っていること
- チーで傾ける牌がおかしい
- 加槓に対応していない

**Comment by youseegreen** [comment]
![image](https://github.com/senskids/CustomMahjong/assets/39123031/51e63793-30da-4d08-8819-d9b77c22f82d)
